import typing as t

__all__ = ['glob', 'iglob', 'makedirs', 'rename', 'symlink']

def glob(pathname: t.AnyStr, *, root_dir: t.AnyStr | None = None, **kwargs: t.Any) -> t.Sequence[str]: ...
def iglob(pathname: t.AnyStr, *, root_dir: t.AnyStr | None = None, **kwargs: t.Any) -> t.Iterator[t.AnyStr]: ...
def makedirs(pathname: t.AnyStr) -> None: ...
def rename(src: t.AnyStr, dst: t.AnyStr) -> None: ...
def symlink(src: t.AnyStr, dst: t.AnyStr) -> None: ...
