networks:
  private:
    internal: true
  public:

volumes:
  ca-certificates:
  kodi-profile:
  wwwdata:
  node_modules:

configs:
  nginx_default:
    file: ./docker/nginx/virtual_host.conf

services:
  nginx:
    image: nginx:1.27-bookworm
    networks:
      private:
        aliases:
          - kyzima-spb.github.io
    configs:
      - source: nginx_default
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ./docker/nginx/generate-cert.sh:/docker-entrypoint.d/99-generate-cert.sh:ro
      - ca-certificates:/usr/local/share/ca-certificates
      - wwwdata:/var/www:ro
    environment:
      REPO_BASE_URL: kyzima-spb.github.io

  kodi:
    image: ghcr.io/kyzima-spb/kodi:bookworm-slim
    networks:
      - private
      - public
    ports:
      - "5900:5900"
      - "9000:9000"
    environment:
      KODI_EXTRA_ARGS: --debug
    volumes:
      - ./docker/kodi/update-cert.sh:/docker-entrypoint.d/99-update-cert.sh:ro
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ca-certificates:/usr/local/share/ca-certificates
      - kodi-profile:/kodi
    depends_on:
      - nginx

  uplayer-web:
    build:
      context: ./addons/plugin.video.uplayer/web/app
      dockerfile: ../Dockerfile
      target: development
    networks:
      - private
      - public
    ports:
      - "127.0.0.1:5173:5173"
    environment:
      VITE_API_URL: "http://127.0.0.1:9000"
    volumes:
      - /app/node_modules
      - ./addons/plugin.video.uplayer/web/app:/app
      - ./addons/plugin.video.uplayer/resources/www:/app/dist

  repo:
    image: python:3.13-slim-bookworm
    networks:
      - private
    environment:
      PATH: /usr/local/bin/scripts:$PATH
    volumes:
      - wwwdata:/var/www
      - ./addons:/var/www/addons:ro
      - ./scripts:/usr/local/bin/scripts:ro
    working_dir: /var/www
    command: sh -c "generate-repository kodi.repository addons/*"
